#!/usr/bin/env bash
set -euo pipefail

# CurAItor installer — macOS and Linux
# Usage: curl -fsSL https://raw.githubusercontent.com/jdidion/curaitor/main/install.sh | bash

VERSION="latest"
INSTALL_DIR="${CURAITOR_DIR:-$HOME/.curaitor}"
REPO="https://github.com/jdidion/curaitor.git"

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m'

log()  { echo -e "${GREEN}[CurAItor]${NC} $*"; }
warn() { echo -e "${YELLOW}[CurAItor]${NC} $*"; }
err()  { echo -e "${RED}[CurAItor]${NC} $*" >&2; }
ask()  { echo -en "${BLUE}[CurAItor]${NC} $* "; }

# --- Detect platform ---
OS="$(uname -s)"
case "$OS" in
  Darwin) PLATFORM="macos" ;;
  Linux)  PLATFORM="linux" ;;
  *)      err "Unsupported platform: $OS"; exit 1 ;;
esac

log "Installing CurAItor on ${PLATFORM}..."

# --- Check prerequisites ---
check_cmd() {
  if ! command -v "$1" &>/dev/null; then
    err "Required: $1 is not installed."
    echo "  $2"
    return 1
  fi
}

MISSING=0
check_cmd "node" "Install Node.js: https://nodejs.org/" || MISSING=1
check_cmd "npm"  "Install Node.js: https://nodejs.org/" || MISSING=1
check_cmd "git"  "Install git: https://git-scm.com/"    || MISSING=1

if [ "$MISSING" -eq 1 ]; then
  err "Please install missing prerequisites and re-run."
  exit 1
fi

NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
  err "Node.js 18+ required (found $(node -v))"
  exit 1
fi

log "Prerequisites OK (node $(node -v), npm $(npm -v))"

# --- Clone or update ---
if [ -d "$INSTALL_DIR/.git" ]; then
  log "Updating existing installation at $INSTALL_DIR..."
  cd "$INSTALL_DIR"
  git pull --quiet origin main
else
  log "Cloning CurAItor to $INSTALL_DIR..."
  git clone --quiet "$REPO" "$INSTALL_DIR"
  cd "$INSTALL_DIR"
fi

# --- Install dependencies ---
log "Installing dependencies..."
npm install --quiet 2>/dev/null

# --- Interactive config ---
ENV_FILE="$INSTALL_DIR/.env"

if [ ! -f "$ENV_FILE" ]; then
  log ""
  echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${PURPLE}  First-time setup${NC}"
  echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""

  # Storage backend
  ask "Storage backend (obsidian/sqlite) [obsidian]:"
  read -r STORAGE_BACKEND
  STORAGE_BACKEND="${STORAGE_BACKEND:-obsidian}"

  VAULT_PATH=""
  PLUGIN_PATH=""
  SQLITE_PATH=""

  if [ "$STORAGE_BACKEND" = "obsidian" ]; then
    # Try to auto-detect vault
    DETECTED_VAULT=""
    if [ "$PLATFORM" = "macos" ]; then
      OBSIDIAN_CONFIG="$HOME/Library/Application Support/obsidian/obsidian.json"
    else
      OBSIDIAN_CONFIG="$HOME/.config/obsidian/obsidian.json"
    fi

    if [ -f "$OBSIDIAN_CONFIG" ]; then
      DETECTED_VAULT=$(python3 -c "
import json, os
with open('$OBSIDIAN_CONFIG') as f:
    cfg = json.load(f)
for v in cfg.get('vaults', {}).values():
    p = v.get('path', '')
    if os.path.isdir(os.path.join(p, 'Curaitor', 'Inbox')) or os.path.isdir(os.path.join(p, 'Curaitor')):
        print(p)
        break
" 2>/dev/null || true)
    fi

    if [ -n "$DETECTED_VAULT" ]; then
      log "Detected Obsidian vault: $DETECTED_VAULT"
      ask "Use this vault? (Y/n):"
      read -r USE_DETECTED
      if [ "${USE_DETECTED:-Y}" != "n" ] && [ "${USE_DETECTED:-Y}" != "N" ]; then
        VAULT_PATH="$DETECTED_VAULT"
      fi
    fi

    if [ -z "$VAULT_PATH" ]; then
      ask "Obsidian vault path:"
      read -r VAULT_PATH
    fi

    ask "CurAItor plugin directory (leave empty to skip):"
    read -r PLUGIN_PATH
  else
    SQLITE_PATH="${INSTALL_DIR}/curaitor.db"
    log "SQLite database will be at: $SQLITE_PATH"
  fi

  # Port
  ask "Server port [3141]:"
  read -r PORT
  PORT="${PORT:-3141}"

  # Write .env
  cat > "$ENV_FILE" <<EOF
# CurAItor configuration (generated by installer)
STORAGE_BACKEND=${STORAGE_BACKEND}
PORT=${PORT}
EOF

  [ -n "$VAULT_PATH" ]  && echo "VAULT_PATH=${VAULT_PATH}" >> "$ENV_FILE"
  [ -n "$PLUGIN_PATH" ] && echo "PLUGIN_PATH=${PLUGIN_PATH}" >> "$ENV_FILE"
  [ -n "$SQLITE_PATH" ] && echo "SQLITE_PATH=${SQLITE_PATH}" >> "$ENV_FILE"

  log "Configuration saved to $ENV_FILE"
  echo ""
else
  log "Using existing config at $ENV_FILE"
fi

# --- Create launcher script ---
BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/curaitor" <<LAUNCHER
#!/usr/bin/env bash
cd "$INSTALL_DIR" && exec npx tsx src/index.ts "\$@"
LAUNCHER
chmod +x "$BIN_DIR/curaitor"

# Check if bin dir is in PATH
if ! echo "$PATH" | grep -q "$BIN_DIR"; then
  warn "Add to your PATH: export PATH=\"$BIN_DIR:\$PATH\""
  warn "  Add this to your ~/.bashrc or ~/.zshrc"
fi

echo ""
echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  CurAItor installed!${NC}"
echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  Start the server:  curaitor"
echo "  Or:                cd $INSTALL_DIR && npm run dev"
echo "  Open:              http://localhost:${PORT:-3141}"
echo ""
echo "  Edit config:       $ENV_FILE"
echo "  Update:            curl -fsSL https://raw.githubusercontent.com/jdidion/curaitor/main/install.sh | bash"
echo ""
