# RSS feeds for /discover
# Imported from Feedly OPML (Science folder) on 2026-03-30

feeds:
- name: genomeweb/channel
  url: https://www.genomeweb.com/channel/all/rss
  category: science
- name: 'bioRxiv Subject Collection: Bioinformatics Genetics Genomics'
  url: http://connect.biorxiv.org/biorxiv_xml.php?subject=bioinformatics+genetics+genomics
  category: science
- name: Nature Genetics
  url: http://feeds.nature.com/ng/rss/current
  category: science
- name: BMC Bioinformatics
  url: http://bmcbioinformatics.biomedcentral.com/articles/most-recent/rss.xml
  category: science
- name: 'Annual Review of Genomics and Human Genetics: Most Recent Articles'
  url: http://www.annualreviews.org/action/showFeed?ui=45mu4&mi=3fndc3&ai=sk&jc=genom&type=etoc&feed=rss
  category: science
- name: Bioinformatics Current Issue
  url: http://bioinformatics.oxfordjournals.org/rss/current.xml
  category: science
- name: Genome Biology
  url: https://genomebiology.biomedcentral.com/articles/most-recent/rss.xml
  category: science
- name: Nat Meth Current Issue
  url: http://feeds.nature.com/nmeth/rss/aop
  category: science
- name: Nat Rev Genetics
  url: http://feeds.nature.com/nrg/rss/current
  category: science
- name: Nature Machine Intelligence
  url: http://feeds.nature.com/natmachintell/rss/current
  category: science
- name: Algorithms In Molecular Biology
  url: http://almob.biomedcentral.com/articles/most-recent/rss.xml
  category: science
- name: Bioinformatics Advance Access
  url: https://academic.oup.com/rss/site_5139/advanceAccess_3001.xml
  category: science
- name: Briefings in Bioinformatics Current Issue
  url: http://bib.oxfordjournals.org/rss/current.xml
  category: science
- name: Nature Biotechnology
  url: http://www.nature.com/nbt/current_issue/rss/
  category: science
